### ISSUE TITLE
Admin styles issue .carbon-hightlight

### ISSUE THREAD

**Issue by edwardhew** [htmlburger/carbon-fields#301]
An issue with the styles.
![highlight-issue](https://user-images.githubusercontent.com/365615/28855999-ff087898-7772-11e7-9cc0-36bd16ea9e44.png)

I am fixing it with custom admin styles, so the use of !important:
```css
.carbon-container .carbon-highlight {
	outline: none !important;
	border: 1px solid #cd4c15 !important;
}
```

Another issue maybe is that the carbon styles `carbon-fields/assets/dist/carbon.css` is loaded with WP's `admin_head` hook instead of `admin_enqueue_scripts`.

If I load my custom CSS with `admin_head` it is placed right above `carbon.css`, if loading with`admin_enqueue_scripts`, it loads way before it.

There is another carbon css file `carbon-fields/core/Libraries/Sidebar_Manager/assets/css/app.css`, it is loaded with `admin_enqueue_scripts`, and I can add mine below it with the 3rd param of `add_action()` like this:

```php
add_action('admin_enqueue_scripts', 'load_my_admin_styles_scripts', 100);
```
