### ISSUE TITLE
Random issue with rich_text fields in tabs

### ISSUE THREAD

**Issue by zevilz** [htmlburger/carbon-fields#410]
This issue is random and only in not first tabs.

Firefox 57. Content not visible in visual mode. Switching to text mode and return fix issue.
![17-11-2017 11-09-47](https://user-images.githubusercontent.com/12094229/32932880-decd7cf6-cb8a-11e7-93bb-0eac5ac35f5a.png)

Chrome 62.0.3202.89. Container height many more than inner content. Switching to text mode and return fix issue.
![17-11-2017 11-27-45](https://user-images.githubusercontent.com/12094229/32933219-8717bd90-cb8b-11e7-9eef-8d9a53beae2c.png)

Both issues don't depend on quantity of content.
CF v.2.1.1

**Comment by edwardhew** [comment]
I use this workaround, CSS enqueued on admin.
```css
.mce-container-body .mce-container iframe {
	min-height: 3em !important;
}
```
Oembed also have similar issue as of 2.1.1, where preview area have no height, doesn't happen every time, manually added to fix.
```css
.carbon-oembed-preview iframe {
	min-height: 338px;
}
```
